### ISSUE TITLE
Loopback device in namespace

### ISSUE THREAD

**Issue by daurnimator** [hashbang/pam_network_namespace#2]

**Comment by KellerFuchs** [comment]
Having a stab at that.

**Comment by daurnimator** [comment]
Cool :)

I couldn't figure out how to do the equivalent of `ip link set lo up`
This is the diff I have sitting around. Maybe it will help you?

``` diff
diff --git a/pam_network_namespace.c b/pam_network_namespace.c
index 811117b..2d79e2e 100644
--- a/pam_network_namespace.c
+++ b/pam_network_namespace.c
@@ -1,3 +1,7 @@
+#include <sys/socket.h> /* needed for linux/if.h */
+#include <linux/if.h> /* IF_OPER_UP */
+#include <netlink/object.h>
+#include <netlink/route/link.h>
 #include <netlink/route/link/veth.h>
 #include <sched.h>
 #include <security/pam_modules.h>
@@ -22,6 +26,7 @@ PAM_EXTERN int pam_sm_open_session(pam_handle_t *pamh, int flags,
    const char *user = NULL;
    int err;
    struct nl_sock *sock = NULL;
+   struct rtnl_link *lo = NULL, *lo_changes = NULL;

    if (PAM_SUCCESS != pam_get_item(pamh, PAM_USER, (const void**) &user) || user == NULL) {
        pam_syslog(pamh, LOG_ERR, "Unable to get username; using auto-generated interface name.");
@@ -43,6 +48,28 @@ PAM_EXTERN int pam_sm_open_session(pam_handle_t *pamh, int flags,
        goto err;
    }

+   /* Bring up loopback device inside namespace
+      equivalent to: ip link set lo up */
+   if (0 != (err = rtnl_link_get_kernel(sock, 1, "lo", &lo))) {
+       pam_syslog(pamh, LOG_ERR, "Unable to get looopback link: %s", nl_geterror(err));
+       goto err;
+   }
+   if (NULL == (lo_changes = (struct rtnl_link*)nl_object_clone((struct nl_object*)lo))) {
+       pam_syslog(pamh, LOG_ERR, "Unable to allocate link");
+       goto err;
+   }
+   printf("NAME: %s\n", rtnl_link_get_name(lo_changes));
+   rtnl_link_set_operstate(lo_changes, IF_OPER_UP);
+   // rtnl_link_set_carrier(lo, IF_OPER_UP);
+   // rtnl_link_set_linkmode(lo, IF_OPER_UP);
+   if (0 != (err = rtnl_link_change(sock, lo, lo_changes, 0))) {
+       pam_syslog(pamh, LOG_ERR, "Unable to bring up loopback interface: %s", nl_geterror(err));
+       goto err;
+   }
+   rtnl_link_put(lo_changes);
+   rtnl_link_put(lo);
+   lo_changes = NULL, lo = NULL;
+
    /* Create veth device shared with parent */
    if (0 != (err = rtnl_link_veth_add(sock, DEFAULT_DEVICE_NAME, user, getppid()))) {
        pam_syslog(pamh, LOG_ERR, "Unable to create veth pair: %s", nl_geterror(err));
@@ -52,6 +79,8 @@ PAM_EXTERN int pam_sm_open_session(pam_handle_t *pamh, int flags,
    return PAM_SUCCESS;

 err:
+   if (lo_changes) rtnl_link_put(lo_changes);
+   if (lo) rtnl_link_put(lo);
    if (sock) nl_socket_free(sock);

    return PAM_SESSION_ERR;
```

IIRC, the rtnl library sets up a series of changes to make in userspace; and then you have to flush them into the kernel. This wasn't very well documented and took me a while to figure out.

**Comment by daurnimator** [comment]
@KellerFuchs did you get anywhere with this?

**Comment by KellerFuchs** [comment]
@daurnimator Not really.  I had a slightly different approach (not cloning the existing interface), but there are some parts I'm just not figuring out from the documentation.
I guess I'll have to ask the `libnl` peeps.

**Comment by daurnimator** [comment]
The cloning wasn't the problem (that bit works!). The remaining issue with the above code was setting the link "up".
I could do it manually with `ip link set lo up`, but I couldn't figure out the libnl code to do the same.

**Comment by anyc** [comment]
In case you're still interested, I struggled with a similar piece of code and it works here now if I simply rtnl_link_alloc() a new "empty" link and call rtnl_link_set_flags(mynewlink, IFF_UP) before the rtnl_link_change() call.

**Comment by daurnimator** [comment]
@anyc I'm not sure I understand:
By allocating a new link and setting that to IFF_UP a *different* link started working?

**Comment by anyc** [comment]
As far as I know, rtnl_link_change will do its work on the interface identified by the first link structure. The second link structure only contains the changes that will by applied to the interface represented by the first link.

**Comment by KellerFuchs** [comment]
@anyc Our plans changed a bit: I started moving the namespace creation and configuration logic in a [shell script](https://github.com/hashbang/shell-etc/pull/103/files#diff-6c4a72f731163dd5bf1daa864956e92b) that gets ran by `pam_exec`.

**Comment by daurnimator** [comment]
@KellerFuchs pam_exec won't work here: `unshare` only works on the current process: there is no way to have it apply to a parent.

**Comment by KellerFuchs** [comment]
@daurnimator Yes, we still need `pam_network_namespace` to make the right `setns(2)` call.
We can still move the whole namespace creation and setup to the shell script, and do something like:
```c
// That's not proper C: it leaks resources and does no error handling
int ns_fd = open(strcat("/var/run/netns/user-", PAM_USER), O_CLOEXEC);
setns(ns_fd, CLONE_NEWNET);
```

**Comment by daurnimator** [comment]
At that point why bother with pam_exec? I'd rather we just do it all in the C module.

**Comment by KellerFuchs** [comment]
Because doing it in a shell script is several orders of magnitude more readable, maintainable, and less error-prone (esp. considering that the alternative is homemade C code running as root)?

Also, `ip(8)` has documentation, unlike `libnl`, so we won't spend even more time blocked on completely basic things (like setting up a loopback interface...).

**Comment by daurnimator** [comment]
> Also, ip(8) has documentation, unlike libnl, so we won't spend even more time blocked on completely basic things (like setting up a loopback interface...).

Can always just call `system()` with the current layout if we don't want to keep trying with libnl

**Comment by KellerFuchs** [comment]
It's not because we can that we should, especially because this belongs more in the realm of configuration than hard-coded in a PAM module.
(Also, what would be the advantage of doing it with `system()` and doing the error-handling in C?)

**Comment by daurnimator** [comment]
Thanks @anyc that worked
